lib/CleantalkSP/Common/Helper.php

- Common\Helper using Singleton trait;
- Common\Helper::ip__get() storing IPs by type;
- Common\Helper::http__get_headers() headers;

New: Common\Helper. Store functions call results.

---

lib/CleantalkSP/Updater/UpdaterScripts.php

Review was approved here: https://github.com/CleanTalk/security-malware-firewall/pull/44

Fix: Scanner. Cleaning from heuristic results.

---

lib/CleantalkSP/SpbctWP/RenameLoginPage.php

Fix. Login page. Warnings if use custom login page url on php >= 8 version.

Fix. Login page. Warnings custom login url on php 8.

---

inc/spbc-scanner.php
inc/spbc-settings.php

https://doboard.com/1/task/1826

File replacement with original fix

---

inc/spbc-scanner.php
inc/spbc-settings.php
lib/CleantalkSP/Common/Scanner/HeuristicAnalyser/Modules/Entropy.php
lib/CleantalkSP/SpbctWP/Scanner/ScannerQueue.php
lib/CleantalkSP/SpbctWP/Scanner/Surface.php

https://doboard.com/1/task/621

Added spbc__get_exists_directories()

---

inc/spbc-settings.php

https://doboard.com/1/task/765

Fixed count outbound links

---

inc/spbc-scanner.php
lib/CleantalkSP/Common/Helpers/HTTP.php
lib/CleantalkSP/Common/Validate.php
lib/CleantalkSP/SpbctWP/Scanner/Frontend.php
lib/CleantalkSP/SpbctWP/Scanner/Helper.php
lib/CleantalkSP/SpbctWP/Scanner/Links.php
lib/CleantalkSP/SpbctWP/Scanner/ScannerQueue.php
lib/CleantalkSP/SpbctWP/Scanner/Stages/SignatureAnalysis/Repository.php

https://doboard.com/1/task/2266
* getContentFromURL refactored, now use getResponseCode as inner check by default
* getResponseCode refactored

HTTP lib refactoring

---

inc/spbc-settings.php
lib/CleantalkSP/SpbctWP/ListTable.php

https://doboard.com/1/task/2469
* Fileds width now can be set up.

Accordeon fields custom length 

---

inc/spbc-scanner.php
inc/spbc-settings.php
security-malware-firewall.php

https://doboard.com/1/task/2472
* New method spbc_get_sql_where_addiction_for_table_of_category() to get common WHERE suffix for table categories.

Bulk actions fixed and improved

---

inc/spbc-admin.php
inc/spbc-settings.php
security-malware-firewall.php

task https://doboard.com/1/task/2242

Fix. Whitelabel. Added rules for check brand info.

---

lib/CleantalkSP/SpbctWP/Firewall/BFP.php
security-malware-firewall.php

task https://doboard.com/1/task/1690

Upd. Firewall. Protect login from brute force even if expired key.

---

inc/spbc-admin.php
inc/spbc-settings.php
lib/CleantalkSP/SpbctWP/Firewall/FirewallModule.php
lib/CleantalkSP/SpbctWP/Firewall/die_page_bfp.html
lib/CleantalkSP/SpbctWP/Firewall/die_page_fw.html
lib/CleantalkSP/SpbctWP/Firewall/die_page_tc.html
lib/CleantalkSP/SpbctWP/Firewall/die_page_waf.html
security-malware-firewall.php

https://doboard.com/1/task/2609

Added constants for custom description and FAQ link

---

lib/CleantalkSP/SpbctWP/Firewall/FW.php

https://doboard.com/1/task/2570

Fix. FW. Delete all lines after send fw logs.

---

inc/spbc-settings.php
lib/CleantalkSP/SpbctWP/Firewall/BFP.php
lib/CleantalkSP/SpbctWP/Scanner/ScannerQueue.php
security-malware-firewall.php
tests/Standalone/TestBFP.php

https://doboard.com/1/task/2863

Mod: Added .otc files for scanning

---

composer.json
inc/spbc-scanner.php
inc/spbc-settings.php
lib/CleantalkSP/SpbctWP/Firewall/BFP.php
tests/Standalone/TestBFP.php

https://doboard.com/1/task/2815
* Added a new notice block to accordions.

Security audit suggestion

---

composer.json
lib/CleantalkSP/SpbctWP/Firewall/BFP.php
lib/CleantalkSP/SpbctWP/Scanner/ScannerQueue.php
tests/Standalone/TestBFP.php

https://doboard.com/1/task/2965
* Mod. Unset 'approved_by_ct' status if the hash no longer persists in the approved hashes list.

Unset approved by ct status if no hash in list

---

lib/CleantalkSP/SpbctWP/Scanner/Frontend.php

https://doboard.com/1/task/2966

Upd. Scan. Find and show all malwares in Frontend Malware accordion.

---

inc/spbc-settings.php

https://doboard.com/1/task/3183

Fixed Security Audit Banner, added this to Suspicious

---

security-malware-firewall.php

https://doboard.com/1/task/3014

AMP integration

---

lib/CleantalkSP/Common/API.php
lib/CleantalkSP/Common/Scanner/SignaturesAnalyser/Controller.php
lib/CleantalkSP/SpbctWP/Scanner/ScannerQueue.php
security-malware-firewall.php

https://doboard.com/1/task/3267

Signatures to cloud aa

---

inc/spbc-settings.php
lib/CleantalkSP/Common/Scanner/HeuristicAnalyser/Controller.php

https://doboard.com/1/task/2979

DANGER files moved to SUSPICIOUS accordion

---

readme.txt

https://doboard.com/1/task/3513

New readme and screenshots.

---

inc/spbc-settings.php
lib/CleantalkSP/SpbctWP/DTO/MScanFilesDTO.php

https://doboard.com/1/task/1861

Allow to send unknown files for analysis

---

inc/spbc-backups.php
inc/spbc-scanner.php

task https://doboard.com/1/task/3870

Update. Scanner. Hidden the listing backups and quarantine directories.

---

lib/CleantalkSP/Common/Scanner/HeuristicAnalyser/HeuristicAnalyser.php
lib/CleantalkSP/Common/Scanner/HeuristicAnalyser/Modules/CodeStyle.php

task https://doboard.com/1/task/3835

Update. Scan. Added check line length and mark of unreadable.

---

lib/CleantalkSP/SpbctWP/Scanner/Frontend.php
lib/CleantalkSP/SpbctWP/Scanner/FrontendScan.php

task https://doboard.com/1/task/4155

Upd. Scan. Keep surroundings code of FMS weak  in db.

---

inc/spbc-settings.php
lib/CleantalkSP/Security/Firewall.php
lib/CleantalkSP/Security/Firewall/FirewallModule.php
lib/CleantalkSP/SpbctWP/DB/SQLSchema.php
lib/CleantalkSP/SpbctWP/Firewall/FW.php
lib/CleantalkSP/SpbctWP/Firewall/WAF.php
lib/CleantalkSP/SpbctWP/Firewall/WafBlocker.php
lib/CleantalkSP/SpbctWP/State.php
lib/CleantalkSP/Updater/UpdaterScripts.php
security-malware-firewall.php

https://doboard.com/1/task/4238

New. FireWall. New module added: `WAF Blocker`.

---

inc/spbc-settings.php

https://doboard.com/1/task/4621

Fix. FireWall. Statuses of the triggered networks displayed.

---

inc/spbc-settings.php

https://doboard.com/1/task/4243

Changes btn settings av

---

inc/fw-update.php
lib/CleantalkSP/SpbctWP/State.php

task https://doboard.com/1/task/4940

New. SecFW. Added last update log.

---

inc/spbc-auth.php
inc/spbc-settings.php

Task https://doboard.com/1/task/5275

Fix. Auth. Change text.

---

inc/spbc-settings.php
inc/spbc-tools.php

https://doboard.com/1/task/5548

Fix. 2FA. Show role Subscriber, correction of user data verification

---

lib/CleantalkSP/Common/Scanner/HeuristicAnalyser/HeuristicAnalyser.php
lib/CleantalkSP/Common/Scanner/HeuristicAnalyser/Modules/CodeStyle.php

https://doboard.com/1/task/5453

Skip files with no PHP code found

---

inc/fw-update.php
inc/spbc-settings.php

https://doboard.com/1/task/4630

Fix. Settings. Show stored IPs count in the `summary` block.

---

inc/fw-update.php

task https://doboard.com/1/task/5182

Update. SecFW. Switch to direct update if updating is freezing.

---

inc/spbc-admin.php
inc/spbc-settings.php
lib/CleantalkSP/SpbctWP/State.php
lib/CleantalkSP/Updater/UpdaterScripts.php

https://doboard.com/1/task/5527

Vulnerability alarm. Settings updates.

---

lib/CleantalkSP/Common/FSWatcher/Service.php
lib/CleantalkSP/Common/FSWatcher/View/Phrases.php
lib/CleantalkSP/Common/FSWatcher/View/View.php
lib/CleantalkSP/Common/FSWatcher/assets/fswatcher-logic.js
lib/CleantalkSP/SpbctWP/FSWatcher/Analyzer/SpbctWpFSWAnalyzer.php
lib/CleantalkSP/SpbctWP/FSWatcher/SpbctWpFSWController.php
lib/CleantalkSP/SpbctWP/FSWatcher/Storage/SpbctWpFSWFileStorage.php
lib/CleantalkSP/SpbctWP/FSWatcher/View/Phrases.php
lib/CleantalkSP/SpbctWP/FSWatcher/View/View.php

Task https://doboard.com/1/task/5888

Upd. FSWatcher. Refactoring settings, add file view, fix dates format.

---

inc/fw-update.php

task https://doboard.com/1/task/5658

Upd. SecFW. Added ipv6 count to summary.

---

lib/CleantalkSP/SpbctWP/Firewall/UploadChecker.php
lib/CleantalkSP/SpbctWP/VulnerabilityAlarm/VulnerabilityAlarm.php
lib/CleantalkSP/SpbctWP/VulnerabilityAlarm/VulnerabilityAlarmService.php

task https://doboard.com/1/task/5164

Upd. Vulnerability alarm. Added check to install and update process.

---

inc/admin-bar.php
inc/spbc-settings.php
lib/CleantalkSP/SpbctWP/FSWatcher/View/Phrases.php
readme.txt

https://doboard.com/1/task/5988

FS Watcher description.

---

lib/CleantalkSP/SpbctWP/VulnerabilityAlarm/VulnerabilityAlarm.php

https://doboard.com/1/task/6072

Fix. Vulnerability alarm. Unexpected type of plugin data handled.

---

lib/CleantalkSP/Common/Scanner/HeuristicAnalyser/Modules/CodeStyle.php

task https://doboard.com/1/task/6039

Upd. Heuristic. Skipping svg in long line check.

---

inc/admin-templates/field-templates/time.php
inc/spbc-settings.php
inc/spbc-tools.php

https://doboard.com/1/task/5927

Fix. Scanner. Auto scan sheduling fixed.

---

inc/spbc-admin.php
inc/spbc-settings.php
lib/CleantalkSP/SpbctWP/VulnerabilityAlarm/VulnerabilityAlarmService.php
lib/CleantalkSP/SpbctWP/VulnerabilityAlarm/VulnerabilityAlarmView.php
security-malware-firewall.php

https://doboard.com/1/task/6247

Vulnerability Alarm. Run cron updating research DB on any plugin installation.

---

lib/CleantalkSP/SpbctWP/Firewall/UploadChecker.php

https://doboard.com/1/task/6216

Fix. RegEx checkVulnerability

---

lib/CleantalkSP/SpbctWP/ListTable.php

https://doboard.com/1/task/6309

New. Removed the limit for links

---

lib/CleantalkSP/Common/Scanner/HeuristicAnalyser/HeuristicAnalyser.php
lib/CleantalkSP/Common/Scanner/HeuristicAnalyser/Modules/CodeStyle.php

https://doboard.com/1/task/6692

Disable long lines detection

---

lib/CleantalkSP/Common/FSWatcher/Analyzer/Analyzer.php
lib/CleantalkSP/Common/FSWatcher/assets/fswatcher-logic.js
lib/CleantalkSP/SpbctWP/FSWatcher/Analyzer/SpbctWpFSWAnalyzer.php
lib/CleantalkSP/SpbctWP/FSWatcher/SpbctWpFSWController.php
readme.txt
security-malware-firewall.php

https://doboard.com/1/task/6712

FSWatcher fix.

---

lib/CleantalkSP/Common/Scanner/HeuristicAnalyser/Structures/FileInfo.php
lib/CleantalkSP/SpbctWP/Firewall/UploadChecker.php
lib/CleantalkSP/SpbctWP/Scanner/DirectoryScan.php
lib/CleantalkSP/SpbctWP/Scanner/ScannerQueue.php
tests/CleantalkSP/SpbctWP/UploadChecker/TestUploadChecker.php
tests/CleantalkSP/SpbctWP/UploadChecker/files/bad_source/plugin_bad.php
tests/CleantalkSP/SpbctWP/UploadChecker/files/good_source/plugin_good.php

https://doboard.com/1/task/6459

Use get_file_data to get the info to check.

---

lib/CleantalkSP/SpbctWP/VulnerabilityAlarm/VulnerabilityAlarmView.php

https://doboard.com/1/task/6482

Research link av

---

lib/CleantalkSP/Common/Scanner/HeuristicAnalyser/HeuristicAnalyser.php
lib/CleantalkSP/Common/Scanner/HeuristicAnalyser/Modules/CodeStyle.php

task https://doboard.com/1/task/2925

Upd. Heuristic. Adding noise param.

---

inc/spbc-scanner.php
lib/CleantalkSP/Common/API.php
lib/CleantalkSP/SpbctWP/DTO/MScanFilesDTO.php

https://doboard.com/1/task/6684

Upd. MScanFilesDTO. Added new fields

---

lib/CleantalkSP/SpbctWP/ListTable.php

https://doboard.com/1/task/776

Fix. Add form for pagination block

---

lib/CleantalkSP/Common/Scanner/HeuristicAnalyser/HeuristicAnalyser.php
lib/CleantalkSP/Common/Scanner/HeuristicAnalyser/Modules/CodeStyle.php

https://doboard.com/1/task/6212

Ref. Unreadable code checking refactored.

---

security-malware-firewall.php

https://doboard.com/1/task/7436

Fix TC block fro admins

---

inc/spbc-settings.php
lib/CleantalkSP/SpbctWP/State.php
security-malware-firewall.php

New. Settings. New endpoint WP 'user' blocking option

---

inc/spbc-settings.php
lib/CleantalkSP/SpbctWP/State.php
lib/CleantalkSP/SpbctWP/VulnerabilityAlarm/VulnerabilityAlarmService.php
lib/CleantalkSP/Updater/UpdaterScripts.php
security-malware-firewall.php

Upd. Summary of vulnerability check results

---

lib/CleantalkSP/SpbctWP/Cron.php

task https://doboard.com/1/task/6428

Fix. Cron. Fixed updateTask function to save the last_call param.

---

inc/spbc-settings.php

Upd. Scanner. Audit banner on unknown list implemented. 

---

inc/spbc-admin.php
inc/spbc-settings.php
inc/spbc-tools.php
lib/CleantalkSP/SpbctWP/DB/SQLSchema.php

Upd. Recording and displaying an event from wp_spbc_auth_logs

---

inc/spbc-settings.php
inc/spbc-tools.php
lib/CleantalkSP/SpbctWP/Firewall/BFP.php
lib/CleantalkSP/SpbctWP/Firewall/FirewallState.php
lib/CleantalkSP/SpbctWP/Firewall/TC.php
lib/CleantalkSP/SpbctWP/Firewall/WafBlocker.php
security-malware-firewall.php
tests/Mock/FirewallStateMock.php
tests/Standalone/TestBFP.php

task https://doboard.com/1/task/6559

Fix. Firewall. Updated logging process.

---

lib/CleantalkSP/SpbctWP/DB/SQLSchema.php
lib/CleantalkSP/Updater/UpdaterScripts.php

https://doboard.com/1/task/7681

Siganture body size extended

---

lib/CleantalkSP/SpbctWP/Scanner/ScannerQueue.php

Fix. Scanner. Reset `weak_spot` and `severity` on modified files.

---

inc/spbc-settings.php
lib/CleantalkSP/SpbctWP/Firewall/UploadChecker.php
lib/CleantalkSP/SpbctWP/Scanner/DirectoryScan.php

Fix. Security. The upload checker used signatures analysis only for now.

---

inc/spbc-settings.php

task https://doboard.com/1/task/8307

Fix. Settings. Updated statement for 2fa.

---

inc/spbc-auth.php

task https://doboard.com/1/task/8306

Fix. Settings. Updated 2fa handler.

---

inc/spbc-firewall.php
lib/CleantalkSP/SpbctWP/Firewall/TC.php
security-malware-firewall.php

task https://doboard.com/1/task/8274

Fix. FW. Update is_admin handler.

---

lib/CleantalkSP/SpbctWP/Scanner/Stages/SignatureAnalysis/Repository.php
lib/CleantalkSP/SpbctWP/State.php

https://doboard.com/1/task/8459

Sigantures V3

---

lib/CleantalkSP/SpbctWP/Firewall.php
lib/CleantalkSP/SpbctWP/Firewall/FW.php

https://doboard.com/1/task/8351

Add signature ID to WAF logs

---

lib/CleantalkSP/Common/FSWatcher/Controller.php
lib/CleantalkSP/Common/FSWatcher/Logger.php
lib/CleantalkSP/SpbctWP/FSWatcher/SpbctWpFSWController.php

https://doboard.com/1/task/8308

Fix. FSWatcher. Logs naming fixed.

---

lib/CleantalkSP/Common/Scanner/HeuristicAnalyser/HeuristicAnalyser.php
lib/CleantalkSP/Common/Scanner/HeuristicAnalyser/Modules/CodeStyle.php

https://doboard.com/1/task/8337

Long lines check enabled

---

lib/CleantalkSP/Security/Firewall.php

https://doboard.com/1/task/8590

Fix. Call function on null

---

inc/spbc-tools.php
lib/CleantalkSP/Common/Helpers/CSV.php
lib/CleantalkSP/SpbctWP/Scanner/Helper.php
lib/CleantalkSP/SpbctWP/Scanner/ScannerQueue.php
lib/CleantalkSP/SpbctWP/Scanner/ScanningLog/Repository.php

task https://doboard.com/1/task/8811

Upd. Scan. Updated flow for upload hashes.

---

inc/spbc-scanner.php
lib/CleantalkSP/SpbctWP/ListTable.php

task https://doboard.com/1/task/7925

Upd. Scan. Updated handler for cloud results method.

---

lib/CleantalkSP/SpbctWP/Scanner/Cure.php
lib/CleantalkSP/SpbctWP/Scanner/CureLog/CureLog.php
lib/CleantalkSP/SpbctWP/Scanner/Stages/CureStage.php

https://doboard.com/1/task/8877

Cure with block comment

---

inc/spbc-admin.php
lib/CleantalkSP/SpbctWP/LinkConstructor.php
lib/CleantalkSP/SpbctWP/Views/Settings.php

https://doboard.com/1/task/8157

Renewal link on top info badge

---

lib/CleantalkSP/Common/API.php
lib/CleantalkSP/SpbctWP/Scanner/Stages/DTO/SendFilesDTO.php
lib/CleantalkSP/SpbctWP/Scanner/Stages/SendResultsStage.php

Upd. MScan logs. Removed sending unknown files

---

lib/CleantalkSP/SpbctWP/FSWatcher/Analyzer/SpbctWpFSWAnalyzer.php

Fsw compare av

---

inc/spbc-settings.php
lib/CleantalkSP/SpbctWP/LinkConstructor.php

Upd. BannerLinks. Compiling links to treatment through class LinkConstructor

---

lib/CleantalkSP/SpbctWP/Scanner/Stages/SignatureAnalysis/Repository.php

Upd. SignatureAnalysis. Removing the link and checking for v0 signatures

---

inc/spbc-settings.php
inc/spbc-tools.php
lib/CleantalkSP/Common/API.php
lib/CleantalkSP/SpbctWP/DB/ColumnCreator.php
lib/CleantalkSP/SpbctWP/DB/SQLSchema.php
lib/CleantalkSP/SpbctWP/DTO/SecurityLogsDTO.php
lib/CleantalkSP/SpbctWP/DTO/SecurityLogsDataRowDTO.php
lib/CleantalkSP/Templates/DTO.php
lib/CleantalkSP/Updater/UpdaterScripts.php
security-malware-firewall.php

https://doboard.com/1/task/8496

Security logs method updates

---

inc/spbc-tools.php

https://doboard.com/1/task/8137#comment_64579

Updated parsing url on admin actions collection

---

inc/spbc-settings.php

https://doboard.com/1/task/9644

Fix. Settings. Url validation

---

inc/admin-bar.php
lib/CleantalkSP/SpbctWP/LinkConstructor.php

https://doboard.com/1/task/8851

New. Admin bar. Promotion link `Manuals and FAQ` added.

---

inc/spbc-firewall.php
security-malware-firewall.php

https://doboard.com/1/task/10756

Skip WAF-only check on admin URI if uesr is not loged in

---

inc/spbc-settings.php
inc/spbc-tools.php

New. Firewall. Deleting todo and adding a description for the table

---

lib/CleantalkSP/SpbctWP/Scanner/DirectoryScan.php
lib/CleantalkSP/SpbctWP/Scanner/ScannerQueue.php
lib/CleantalkSP/SpbctWP/Scanner/Stages/SendResultsStage.php
tests/Surface/SurfaceTest.php

https://doboard.com/1/task/7724

Fix. Scanner. JS extension excluded from scanner.

---

lib/CleantalkSP/SpbctWP/Scanner/Stages/CureStage.php

https://doboard.com/1/task/9052

Fix. Scanner. Manual cure logic fixed - added stage creating a backup.

---

inc/spbc-scanner.php
lib/CleantalkSP/SpbctWP/ListTable.php

https://doboard.com/1/task/9176

Mod. ButtonAction. Checking for the existence of a file and deleting it from the log
